version: '3.8'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${RADARR_CONFIG:-./jellyfin/radarr}:/config
      - ${MOVIES_VOLUME:-./JellyfinData/movies}:/movies
      - ${DOWNLOADS_VOLUME:-./jellyfin/downloads}:/downloads
    ports:
      - ${RADARR_PORT:-7878}:7878
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${SONARR_CONFIG:-./jellyfin/sonarr}:/config
      - ${TVSERIES_VOLUME:-./JellyfinData/tvseries}:/tv
      - ${DOWNLOADS_VOLUME:-./jellyfin/downloads}:/downloads
    ports:
      - ${SONARR_PORT:-8989}:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${PROWLARR_CONFIG:-./jellyfin/prowlarr}:/config
    ports:
      - ${PROWLARR_PORT:-9696}:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ:-Etc/UTC}
    ports:
      - ${FLARESOLVERR_PORT:-8191}:8191
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${QBITTORRENT_CONFIG:-./jellyfin/qBittorrent/appdata}:/config
      - ${DOWNLOADS_VOLUME:-./jellyfin/downloads}:/downloads #optional
    ports:
      - ${QBITTORRENT_PORT:-8080}:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyseer:
    image: fallenbagel/jellyseerr:latest	
    container_name: jellyseer
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${JELLYSEER_CONFIG:-./jellyfin/jellyseer}:/config
    ports:
      - ${JELLYSEER_PORT:-5055}:5055
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${JELLYFIN_CONFIG:-./jellyfin/jellyfin}:/config
      - ${TVSERIES_VOLUME:-./JellyfinData/tvseries}:/data/tvshows
      - ${MOVIES_VOLUME:-./JellyfinData/movies}:/data/movies
    ports:
      - ${JELLYFIN_PORT:-8096}:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped